baseURL = "/"
buildDrafts = false
buildExpired = false
buildFuture = false
enableRobotsTXT = true
paginate = 100
pygmentsUseClasses = true
theme = "PaperMod"
title = "FOIA"

[permalinks]
posts = "/:year/:month/:title"


[params]
DateFormat = "January 2, 2006"
ShowBreadCrumbs = true
ShowPostNavLinks = true
ShowRssButtonInSectionTermList = true
defaultTheme = "auto"
description = "SEC FOIA requests submitted by a retail investor"
env = "production"
title = "Freedom of Information"
hideFooter = true

[params.homeInfoParams]
Content = "Documentation of FOIA request/responses between a retail investor and the SEC."
Title = "What is this?"

[params.editPost]
Text = "Suggest Changes"
URL = "https://github.com/connyay/foia/tree/main/content"
appendFilePath = true

# [[menu.main]]
# identifier = "categories"
# name = "Categories"
# url = "/categories/"
# weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20
